# app will look to X-Forwarded-Protocol and X-Forwarded-host when
# constructing URLs?
behind_proxy: 1

# app should consider all warnings as blocking errors?
warnings: 0

# which logger to use?
logger: 'file'

# which log messages should be actually logged?
log: 'warning'

# app will render a detailed debug screen whenever an error is caught?
show_errors: 0

# app will reload the route handlers whenever the file where they are
# defined is changed?
auto_reload: 0

# cache route resolution for maximum performance?
route_cache: 1
